import os
from PySide6.QtCore import QThread, Signal
from datetime import datetime

# TRY/EXCEPT for ReportLab to prevent crashes if missing
try:
    from reportlab.lib.pagesizes import letter
    from reportlab.pdfgen import canvas
    from reportlab.lib import colors
    REPORTLAB_AVAILABLE = True
except ImportError:
    REPORTLAB_AVAILABLE = False

class ReportWorker(QThread):
    log_signal = Signal(str)
    progress_signal = Signal(int)
    finished_signal = Signal(bool, str)

    def __init__(self, project_data):
        super().__init__()
        self.data = project_data
        self.base_path = os.getcwd()
        self.output_dir = os.path.join(self.base_path, "results", "reports")
        os.makedirs(self.output_dir, exist_ok=True)

    def run(self):
        self.log_signal.emit("🚀 Initializing Report Generator...")
        self.progress_signal.emit(10)

        if not REPORTLAB_AVAILABLE:
            self.log_signal.emit("❌ Error: 'reportlab' library missing. Run 'pip install reportlab'")
            self.finished_signal.emit(False, "")
            return

        p_name = self.data.get('project_name', 'Unknown_Project')
        pdf_path = os.path.join(self.output_dir, f"Report_{p_name}.pdf")
        
        try:
            c = canvas.Canvas(pdf_path, pagesize=letter)
            width, height = letter

            # --- HEADER ---
            c.setFillColor(colors.darkblue)
            c.rect(0, height - 100, width, 100, fill=True, stroke=False)
            
            c.setFillColor(colors.white)
            c.setFont("Helvetica-Bold", 24)
            c.drawString(50, height - 60, "MicroGenome Analysis Report")
            
            c.setFont("Helvetica", 14)
            c.drawString(50, height - 85, f"Project: {p_name}")
            
            # --- BODY ---
            c.setFillColor(colors.black)
            y = height - 150
            
            # Basic Info
            c.setFont("Helvetica-Bold", 16)
            c.drawString(50, y, "1. Project Summary")
            y -= 30
            
            c.setFont("Helvetica", 12)
            c.drawString(70, y, f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M')}")
            y -= 20
            c.drawString(70, y, f"File Path: {self.data.get('file_path', 'N/A')}")
            y -= 20
            c.drawString(70, y, f"File Size: {self.data.get('file_size', 0) / 1024:.2f} KB")
            y -= 40

            # Annotation Stats (if available)
            if 'genes' in self.data:
                c.setFont("Helvetica-Bold", 16)
                c.drawString(50, y, "2. Genome Annotation Stats")
                y -= 30
                
                stats = [
                    f"Gene Count: {self.data.get('genes', 0)}",
                    f"GC Content: {self.data.get('gc', 0):.2f}%",
                    f"Proteins: {self.data.get('annotated', 0)}",
                    f"tRNA/rRNA: {self.data.get('rna', 0)}"
                ]
                
                c.setFont("Helvetica", 12)
                for stat in stats:
                    c.drawString(70, y, f"• {stat}")
                    y -= 20
            
            # Footer
            c.setFont("Helvetica-Oblique", 10)
            c.setFillColor(colors.gray)
            c.drawString(50, 50, "Generated by MicroGenome Analyzer Pro v1.0")
            
            c.save()
            
            self.progress_signal.emit(100)
            self.finished_signal.emit(True, pdf_path)

        except Exception as e:
            self.log_signal.emit(f"❌ PDF Generation Failed: {e}")
            self.finished_signal.emit(False, "")